language: node_js
cache: npm
node_js:
  - node
git:
  depth: 5

jobs:
  include:
    - stage: test
      script: npm test

stages:
  - name: deploy
    if: branch = master

deploy:
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm run release
