language: node_js
cache: npm
node_js:
  - node
git:
  depth: 5

jobs:
  include:
    - stage: build
      script:
        - npm run build
        - npm test
        - npm run size
    - stage: release
      script: echo "HELO FROM RELEASE"

stages:
  - build
  - name: release
    if: branch = master AND commit_message !~ /(no-release)/
