language: node_js
cache: npm
node_js:
  - node
git:
  depth: 5

jobs:
  include:
    - stage: build
      name: "Build and test"
      script:
        - npm run build
        - npm test
        - npm run size
    - stage: release
      name: "Release it"
      script:
        - npm run build
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm run release -- --ci

stages:
  - build
  - name: release
    if: branch = master AND commit_message !~ /(no-release)/
